# PostgreSQL Database
DB_HOST = db.uxtddangntejpwaovnmv.supabase.co
DB_NAME = postgres
DB_USER = postgres
DB_PASSWORD= @db.uxtddangntejpwaovnmv.supabase.co5432postgres
DB_PORT = 5432

# Sigfox Credentials
SIGFOX_LOGIN = reece@acucomm.co.za
SIGFOX_PASSWORD = Acucomm@2808
SIGFOX_DEVICE_TYPE = your_device_type